name: Bug report
description: Create a report to help us improve

body:
 - type: textarea
   attributes:
    label: Describe the bug
    description: In you own words, what are you experiencing?
   validations:
    required: true
 - type: input
   attributes:
    label: Your browser and device
    description: On what browser(s) and device (desktop, mobile) do you encounter the issue?
   validations:
    required: true
 - type: textarea
   attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
     1.
     2.
     3.
     ...
    render: bash
   validations:
    required: true
 - type: textarea
   attributes:
    label: Expected behavior
    description: What should have happened instead?
   validations:
    required: false
 - type: textarea
   attributes:
    label: Additional notes
    description: Any additional context that could be helpful?
   validations:
    required: false
