name: "Reset staging to main"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git push origin main:staging --force
