name: "Restart official instance on releases"
on:
  release:
permissions:
  contents: read

jobs:
  restart-on-release:
    runs-on: ubuntu-latest
    if: github.repository == 'letsblockit/letsblockit'
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps restart lbi-prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
